# EPICS IOC Startup Script generated by https://github.com/epics-containers/ibek

cd "/epics/ioc"

epicsEnvSet EPICS_TZ GMT0BST
epicsEnvSet EPICS_CA_MAX_ARRAY_BYTES 3000000

dbLoadDatabase dbd/ioc.dbd
ioc_registerRecordDeviceDriver pdbbase

# aravisConfig(const char *portName, const char *cameraName, size_t maxMemory, int priority, int stackSize)
aravisConfig("DET.CAM", "192.168.250.3", -1, 0, 1)
# NDPvaConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, pvName, maxBuffers, maxMemory, priority, stackSize)
NDPvaConfigure("DET.PVA", 2, 0, "DET.CAM", 0, BL47P-EA-DET-01:TX:PVA, 0, 0, 0, 0)
startPVAServer
# NDPosPluginConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize)
NDPosPluginConfigure("DET.POS", 2, 0, "DET.CAM", 0, 0, 0, 0, 0)
# NDFileHDF5Configure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr)
NDFileHDF5Configure("DET.HDF", 2, 0, "DET.CAM", 0)
# NDStdArraysConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxThreads)
NDStdArraysConfigure("DET.ARR", 2, 0, "DET.CAM", 0, 0, 0, 0, 0, 1)

dbLoadRecords /ioc.db
iocInit


dbpf "BL47P-EA-DET-01:DET:TriggerSource" ""Line1""
dbpf "BL47P-EA-DET-01:DET:GC_GevSCPSPacketSize" "1500"

