##### build stage ##############################################################

ARG BASE
ARG REGISTRY
ARG TARGET_ARCHITECTURE

FROM  ${REGISTRY}/epics-base-${TARGET_ARCHITECTURE}-developer:${BASE} AS developer

RUN pip install --upgrade ibek

# In a devcontainer this folder is mounted on the host's clone of ioc-adsimdetector
WORKDIR /epics/ioc-adsimdetector/ibek-support

# copy the global ibek files
COPY ibek-support/_global/ _global

# busy depends on asyn and autosave
COPY ibek-support/asyn/ asyn/
RUN asyn/install.sh R4-42
COPY ibek-support/autosave/ autosave/
RUN autosave/install.sh R5-10-2

COPY ibek-support/busy/ busy/
RUN busy/install.sh R1-7-3

# Make the IOC
RUN ibek ioc build

##### runtime preparation stage ################################################

FROM developer AS runtime_prep

# get the products from the build stage and reduce to runtime assets only
RUN ibek ioc extract-runtime-assets /assets

##### runtime stage ############################################################

FROM ${REGISTRY}/epics-base-${TARGET_ARCHITECTURE}-runtime:${BASE} AS runtime

# get runtime assets from the preparation stage
COPY --from=runtime_prep /assets /

# install runtime system dependencies, collected from install.sh scripts
RUN ibek support apt-install --runtime

ENV TARGET_ARCHITECTURE ${TARGET_ARCHITECTURE}

ENTRYPOINT ["/bin/bash", "-c", "${IOC}/start.sh"]
