# EPICS IOC Startup Script generated by https://github.com/epics-containers/ibek

cd "/epics/ioc"

epicsEnvSet EPICS_TZ GMT0BST
epicsEnvSet EPICS_CA_MAX_ARRAY_BYTES 3000000

dbLoadDatabase dbd/ioc.dbd
ioc_registerRecordDeviceDriver pdbbase

# aravisConfig(const char *portName, const char *cameraName, size_t maxMemory, int priority, int stackSize)
aravisConfig("DET2.CAM", "192.168.250.28", -1, 0, 1)
# NDPvaConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, pvName, maxBuffers, maxMemory, priority, stackSize)
NDPvaConfigure("DET.PVA", 2, 0, "DET2.CAM", 0, BL47P-EA-DET-02:TX:PVA, 0, 0, 0, 0)
startPVAServer

dbLoadRecords /ioc.db
iocInit


dbpf "BL47P-EA-DET-02:DET:TriggerSource" ""FixedRate""
dbpf "BL47P-EA-DET-02:DET:GC_GevSCPSPacketSize" "1500"
dbpf "BL47P-EA-DET-02:DET:ColorMode" ""RGB1""
dbpf "BL47P-EA-DET-02:DET:AcquireTime" "0.5"

