# discover in which ibek-support* folder the module is defined and apply
# the support variables from ibek-support*/<module>/<module>.install.yml

- name: Find the ibek-support* folder for {{ module }}
  ansible.builtin.shell: ls -d {{ all_root }}/ibek-support*/{{ module }}
  register: module_exists
  changed_when: false

- name: Make sure it was found
  ansible.builtin.fail:
    msg: Module {{ module }} not found (or duplicated) in ibek-support* folders
  when: module_exists.stdout_lines | length != 1

- name: Set the correct ibek-support folder
  ansible.builtin.set_fact:
    ibek_support_folder: "{{ module_exists.stdout_lines[0] }}"

- name: Report the ibek-support folder
  ansible.builtin.debug:
    msg: "ibek_support_folder: {{ ibek_support_folder }}"

- name: Ensure root vars folder exists
  ansible.builtin.file:
    dest: "{{ ansible_root }}/vars"
    state: directory
    mode: "0755"

# because ansible only loads vars from inside the root anisble folder!
- name: Copy module vars into ansible folder for {{ module }}
  ansible.builtin.copy:
    src: "{{ ibek_support_folder }}/{{ module }}.install.yml"
    dest: "{{ ansible_root }}/vars/.tmp.install.yml"
    force: true
    mode: "0644"

- name: Read in the support module vars for {{ module }}
  ansible.builtin.include_vars:
    file: "{{ ansible_root }}/vars/.tmp.install.yml"
