- name: Build Andor SDK2 vendor library
  ansible.builtin.shell:
    cmd: |
      set -e
      git clone -b "2-102dls4" https://gitlab.diamond.ac.uk/controls/support/andorCCDSDK
      mkdir -p /usr/local/andor2/lib64
      cp -r andorCCDSDK/sdk_libs/linux-x86_64/. /usr/local/andor2/lib64/
      mkdir -p /usr/local/andor2/include
      cp -r andorCCDSDK/sdk_include/. /usr/local/andor2/include/
      mkdir -p /usr/local/andor2/etc
      cp -r andorCCDSDK/andorCCDSDKApp/src/sdk/andor/etc/. /usr/local/andor2/etc/
      echo /usr/local/andor2/lib64 > /etc/ld.so.conf.d/andor2.conf
      ldconfig
    executable: /bin/bash
    chdir: /usr/local