# - name: Symlink the video capture device to andor PCI frame grabber card
#   ansible.builtin.file:
#     src: "/dev/video0"
#     dest: "/dev/andor3pci"
#     state: link
#     # when the container launches with device mounted we will have a good link
#     force: yes