# a Role to build all support modules listed in the Dockerfile

- name: Discover modules in Dockerfile
  ansible.builtin.shell: |
    set -e -o pipefail
    cat {{ all_root }}/Dockerfile | sed -n 's/^RUN *ansible.sh \([^ ]*\).*$/\1/p'
  args:
    executable: /bin/bash
  register: modules
  changed_when: false

- name: Report modules
  ansible.builtin.debug:
    msg: "{{ modules.stdout_lines }}"
  changed_when: false

- name: Loop over the support modules in Dockerfile order
  ansible.builtin.include_tasks:
    file: one_support.yml
  loop: "{{ modules.stdout_lines }}"
  loop_control:
    loop_var: module
  when: modules.stdout_lines | length > 0 and module != "ioc"
