- name: Read in default values for all vars
  ansible.builtin.include_vars:
    file: ../support/vars/main.yml

- name: Ensure root vars folder exists
  ansible.builtin.file:
    dest: "{{ ansible_root }}/vars"
    state: directory
    mode: "0755"

- name: Copy module vars into ansible folder for {{ module }}
  ansible.builtin.copy:
    src: "{{ ibek_support_folder }}/{{ module }}.install.yml"
    dest: "{{ ansible_root }}/vars/.tmp.install.yml"
    force: true
    mode: "0644"

- name: Read in the support module vars for {{ module }}
  ansible.builtin.include_vars:
    file: "{{ ansible_root }}/vars/.tmp.install.yml"

- name: Run the support role with correct vars for {{ module }}
  ansible.builtin.include_role:
    name: support
