- name: Build aravis vendor library
  ansible.builtin.shell:
    cmd: |
      setopt -e
      git clone -b "0.8.31" --depth 1 https://github.com/AravisProject/aravis
      cd aravis
      meson build
      cd build
      ninja
      ninja install
      rm -fr /usr/local/aravis
      echo /usr/local/lib64 > /etc/ld.so.conf.d/usr.conf
      cd
      ldconfig
    executable: /bin/bash
    chdir: /usr/local
