- name: Build block
  tags: [do_build]
  block:
    - name: Clean module for rebuild - {{ module }}
      ansible.builtin.command: make clean
      args:
        chdir: "{{ local_path }}"
      changed_when: true

    - name: Build module {{ module }}
      ansible.builtin.command: make {{ make_options }}
      args:
        chdir: "{{ local_path }}"
      changed_when: true

    - name: Clean module {{ module }}
      ansible.builtin.command: make clean
      args:
        chdir: "{{ local_path }}"
      register: build
      ignore_errors: true
      changed_when: true
      when:
        - not skip_clean
