- name: Clone block
  tags: [clone]
  block:
    - name: Clone module to {{ local_path }}
      ansible.builtin.git:
        repo: "{{ organization }}/{{ module }}"
        dest: "{{ local_path }}"
        version: "{{ version }}"
        update: "{{ force_clone | bool }}"
        # use shallow clone unless we want a specific commit
        depth: "{{ 0 if patch_file.when | default(false) | bool else 1 }}"

    # get a specific commit to apply a patch
    - name: Get specific commit to prepare for patch
      ansible.builtin.git:
        repo: "{{ organization }}/{{ module }}"
        dest: "{{ local_path }}"
        version: "{{ patch_file.commit }}"
        force: true
      when:
        - patch_file.when | default(false) | boo
        - patch_file.commit is defined

    - name: Patch file
      ansible.builtin.patch:
        src: "{{ ibek_support_folder }}/{{ patch_file.path }}"
        dest: "{{ local_path }}"
      when:
        - patch_file.when | default(false) | bool
        - patch_file.path is defined
