- name: Clone block
  tags: [clone]
  block:
    - name: Check if the repo has already been cloned
      ansible.builtin.stat:
        path: "{{ local_path }}"
      register: stat_result

    - name: Clone {{ git_repo ~ " vers " ~ version ~ " to " ~ local_path }}
      ansible.builtin.git:
        repo: "{{ git_repo }}"
        dest: "{{ local_path }}"
        version: "{{ version }}"
        recursive: "{{ recursive | default(false) | bool }}"
        depth: "{{ 0 if patch_file.when | default(false) | bool else 1 }}"
      when:
        - not stat_result.stat.exists

    # get a specific commit to apply a patch
    - name: Get specific commit to prepare for patch for {{ module }}
      ansible.builtin.git:
        repo: "{{ git_repo }}"
        dest: "{{ local_path }}"
        version: "{{ patch_file.commit }}"
        force: true
      when:
        - patch_file.when | default(false) | bool
        - patch_file.commit is defined
        - not stat_result.stat.exists

    - name: Patch file for {{ module }} # noqa command-instead-of-module
      ansible.builtin.command: >
        git apply "{{ ibek_support_folder }}/{{ patch_file.path }}"
      args:
        chdir: "{{ local_path }}"
      when: patch_file.when | default(false) and not stat_result.stat.exists | bool
      changed_when: true
