# get all system dependencies

- name: System block
  tags: [system]
  when: not skip_apt
  block:
    - name: Check for apt cache sentinel
      ansible.builtin.stat:
        path: /tmp/.apt_cache_updated
      register: apt_cache_updated_sentinel

    - name: Update apt cache once per container build
      ansible.builtin.apt:
        update_cache: true
      when:
        - is_linux
        - not apt_cache_updated_sentinel.stat.exists

    - name: Create apt cache sentinel
      ansible.builtin.file:
        path: /tmp/.apt_cache_updated
        state: touch
        mode: "0644"
      when:
        - is_linux
        - not apt_cache_updated_sentinel.stat.exists
      changed_when: false

    - name: Download additional files for {{ module }}
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
        mode: "0644"
      loop: "{{ download_extras }}"

    - name: Install system dependencies from registries {{ module }}
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: "{{ apt_developer }}"
      when:
        - not item.startswith('/')
        - is_linux

    - name: Install local system dependencies {{ module }}
      ansible.builtin.package:
        deb: "{{ item }}"
        state: present
      loop: "{{ apt_developer }}"
      ignore_errors: true # local packages may already be installed
      when:
        - item.startswith('/')
        - is_linux

    - name: Register system dependencies for the runtime stage {{ module }}
      ansible.builtin.lineinfile:
        path: "{{ configure_folder }}/runtime_debs"
        # note \Q...\E is used to escape the string
        regexp: "^{{ item | regex_escape() }}$"
        line: "{{ item }}"
        create: true
        mode: "0644"
      loop: "{{ apt_runtime }}"
      when: is_linux
