- name: Install support module {{ module_name }}
  hosts: localhost
  # Use tasks with include_role instead of direct use of playbook roles.
  # Avoids verbose 'skipping' of all tasks in the roles that are not needed.
  tasks:
    - name: All support modules
      ansible.builtin.include_role:
        name: all_support
      when: module_name == "all"

    - name: Find support module yml
      ansible.builtin.include_role:
        name: find
      when: module_name not in ["all", "ioc"]
      vars:
        module: "{{ module_name }}"

    - name: Support module build
      ansible.builtin.include_role:
        name: support
      when: module_name not in ["all", "ioc"]

    - name: Ioc build
      ansible.builtin.include_role:
        name: ioc
      when: module_name in ["all", "ioc"]
