# EPICS IOC Startup Script generated by https://github.com/epics-containers/ibek

cd "/epics/ioc"

epicsEnvSet EPICS_TZ GMT0BST
epicsEnvSet EPICS_CA_MAX_ARRAY_BYTES 3000000

dbLoadDatabase dbd/ioc.dbd
ioc_registerRecordDeviceDriver pdbbase

# Create IP Port (PortName, IPAddr)
pmacAsynIPConfigure("BRICK1port", "192.168.250.13:1025")
# Configure Model 3 Controller Driver (ControlerPort, LowLevelDriverPort, Address, Axes, MovingPoll, IdlePoll)
pmacCreateController("BRICK1", "BRICK1port", 0, 4, 100, 1000)
# Configure Model 3 Axes Driver (Controler Port, Axis Count)
pmacCreateAxes("BRICK1", 4)
# Create CS (CSPortName, ControllerPort, CSNumber, ProgramNumber)
pmacCreateCS("CS1", "BRICK1", 1, 10)
# Configure Model 3 CS Axes Driver (CSPortName, CSAxisCount)
pmacCreateCSAxes("CS1", 9)
pmacDisableLimitsCheck("BRICK1", 2, 0)

dbLoadRecords /ioc.db
iocInit

