# a workflow to check that every support module listed can build
# in an epics base container.
#
# at present this requires the epics-base:7.0.9ad3 container because
# ADCore requires pvaCpp, also ffmpegServer only builds in Ubuntu 22.04
# and not the latest 24.04 used by epics-base:7.0.9ec3
#
name: Build all support modules

on:
  push:
  pull_request:

jobs:
  docker-build-all:
    # pull requests are a duplicate of a branch push if within the same repo.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest

    steps:
      - name: Setup docker (missing on MacOS)
        if: runner.os == 'macos'
        uses: docker-practice/actions-setup-docker@fd7ecdac7caf8e2c541a48c9bcc280aae59a8461

      - name: Log in to GitHub GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ci_test
          load: true
